### ISSUE TITLE
Luzern is broken

### ISSUE THREAD

**Issue by SpiGAndromeda** [Rudd-O/homeassistant-meteoswiss#32]
When trying to add the weather station LUZ (Luzern), the integration won't start. I enabled debug logging but there is no error in the log. It's very specific to this single station. Every other station is working just fine.

These are the configuration screens/data I used.
![image](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/15141351/22be68a3-ff9b-4fce-8fcf-6856b7d51e88)
![image](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/15141351/ba3ad4f1-1a05-473a-a5fc-9b546f931f92)

This is the result.
![image](https://github.com/Rudd-O/homeassistant-meteoswiss/assets/15141351/07b7fd29-a90f-4dbe-b2bb-ce88ed962159)

It loops endless. I already tried to rename the entities during configuration and afterwards without any effect.

**Comment by Rudd-O** [comment]
I suspect this must have been fixed already because I cannot reproduce it.  Please upgrade (redownload) the integration to the latest version, then please try again.  If you must delete the integration config entry and recreate it, then do so.

Next time please submit error logs of your HA instance to make diagnosis possible.
